version: '3.8'

services:
# ---------------------------------------------------------------------------- #
#                                 Java                                         #
# ---------------------------------------------------------------------------- #
    java:
        container_name: 'java'
        image: 'eclipse-temurin:17-jdk-jammy'
        volumes:
            - './backend:/var/www/html'
        command: 'tail -f /dev/null'
        ports:
           - '8081:8081'
        restart: unless-stopped
# ---------------------------------------------------------------------------- #
#                                 Frontend                                     #
# ---------------------------------------------------------------------------- #
    frontend:
        container_name: 'frontend-java'
        image: 'dev-build/frontend-java'
        build:
            context: './frontend'
            dockerfile: Dockerfile.dev
        volumes:
            - './frontend:/var/www/html'
        ports:
           - '3000:3000'
        restart: unless-stopped
