version: '3.8'

services:
# ---------------------------------------------------------------------------- #
#                                 Traefik                                      #
# ---------------------------------------------------------------------------- #
    proxy:
        container_name: 'proxy'
        image: 'traefik:v2.9.6'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        command: 
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--log.level=DEBUG'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        restart: unless-stopped
# ---------------------------------------------------------------------------- #
#                                 Java                                         #
# ---------------------------------------------------------------------------- #
    backend:
        container_name: 'backend'
        image: 'eclipse-temurin:17-jdk-jammy'
        volumes:
            - './backend:/var/www/html'
        command: 'tail -f /dev/null'
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.backend.entrypoints=web'
            - 'traefik.http.routers.backend.rule=Host(`backend.local`)'
            - 'traefik.http.routers.backend.service=backend'
            - 'traefik.http.services.backend.loadbalancer.server.port=8081'

            - 'traefik.http.routers.frontend-api.entrypoints=web'
            - 'traefik.http.routers.frontend-api.rule=Host(`frontend.local`) && (PathPrefix(`/api`) || PathPrefix(`/websocket`))'
            - 'traefik.http.routers.frontend-api.service=frontend-api'
            - 'traefik.http.services.frontend-api.loadbalancer.server.port=8081'
# ---------------------------------------------------------------------------- #
#                                 Frontend                                     #
# ---------------------------------------------------------------------------- #
    frontend:
        container_name: 'frontend'
        image: 'dev-build/frontend-java'
        build:
            context: './frontend'
            dockerfile: Dockerfile
        volumes:
            - './frontend:/var/www/html'
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.frontend.entrypoints=web'
            - 'traefik.http.routers.frontend.rule=Host(`frontend.local`)'
            - 'traefik.http.routers.frontend.service=frontend'
            - 'traefik.http.services.frontend.loadbalancer.server.port=3000'
# ---------------------------------------------------------------------------- #
#                                 Mailcatcher                                  #
# ---------------------------------------------------------------------------- #
    mailcatcher:
        container_name: 'mailcatcher'
        image: 'dockage/mailcatcher:0.9.0'
        restart: unless-stopped
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.mailcatcher.entrypoints=web'
            - 'traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.local`)'
            - 'traefik.http.routers.mailcatcher.service=mailcatcher'
            - 'traefik.http.services.mailcatcher.loadbalancer.server.port=1080'