spring:
  mail:
    host: mailcatcher
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
  datasource:
    # url: jdbc:h2:file:/var/www/html/data/ticketing-system-service
    url: jdbc:h2:mem:ticketing-system-service
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baselineOnMigrate: true
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    mapping-resources:
      - hibernate/user.orm.xml
      - hibernate/customer.orm.xml
      - hibernate/agent.orm.xml
      - hibernate/message.orm.xml
      - hibernate/conversation_status.orm.xml
      - hibernate/conversation.orm.xml
  security:
    user:
      password: "user123"

jwt:
  secret: H3l1oT0JWTeeeeeeeccccccccccccaaaaaaaa

server:
  port : 8081